name: run-tests-on-push
on: [push]
jobs:
    run-backend-tests:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with: 
                distribution: 'oracle'
                java-version: '17' 
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Run backend tests
              run: cd backend && ./gradlew test
